Update uploadFile
wix/media-platform-php-sdk pull request #21
Opened 2022-02-07 02:40 UTC by MikhailoKhraban

2022-02-07 08:25 UTC, Elad-Laufer requested changes

2022-02-07 08:25 UTC, Elad-Laufer commented on lib/Management/FileUploader.php
> +        $options['lifecycle'] = ['age' => 30, 'action' => 'delete'];
Remove this, any file file uploaded will be deleted after 30 minutes.

2022-02-07 08:25 UTC, Elad-Laufer commented on lib/Management/FileUploader.php
>      public function uploadFile($path, $mimeType, $source, $acl = null, $options = []) {
The default should be explicit, and I recommend to default to 'private'

2022-02-07 08:25 UTC, Elad-Laufer commented on lib/Tus/TusClient.php
> +class TusClient
Why not encapsulate https://github.com/ankitpokhrel/tus-php ?

2022-02-07 08:49 UTC, lelikg requested changes
1. there are no tests
2. some other minor changes

2022-02-07 08:49 UTC, lelikg commented on lib/Tus/TusClient.php
> +    protected function finilize($url, $options) {
```suggestion
    protected function finalize($url, $options) {
```

2022-02-07 08:49 UTC, lelikg commented on lib/Tus/TusClient.php
> +?>
please don't leave closing tags in php files

2022-02-08 08:48 UTC, lelikg approved these changes

2022-02-08 10:50 UTC, merged